name: GadgetsMenu
main: com.OnlyNoobDied.GadgetsMenu.GadgetsMenu
version: 3.5.0
auther: OnlyNoobDied, YapZhenYie
description: Amazing hub perks for Donor.
softdepend: [LibsDisguises]
commands:
  menu:
    description: GadgetsMenu Main command.
    aliases: [gmenu, gadgetsmenu]
    usage: /<command>
permissions:
  gadgetsmenu.*:
    default: op
    children:
      - gadgetsmenu.commands.*
      - gadgetsmenu.hats.*
      - gadgetsmenu.particles.*
      - gadgetsmenu.wardrobe.*
      - gadgetsmenu.discoarmor.*
      - gadgetsmenu.gadgets.*
      - gadgetsmenu.emotes.*
      - gadgetsmenu.banners.*
      - gadgetsmenu.morphs.*
      - gadgetsmenu.pets.*
  gadgetsmenu.commands.*:
    default: op
    description: Let a player to use all GadgetsMenu commands.
    children:
      - gadgetsmenu.commands.admin
      - gadgetsmenu.commands.checkupdate
      - gadgetsmenu.commands.addcredits
      - gadgetsmenu.commands.checkcredits
      - gadgetsmenu.commands.paycredits
      - gadgetsmenu.commands.removecredits
      - gadgetsmenu.commands.setcredits
      - gadgetsmenu.commands.givemenu
      - gadgetsmenu.commands.help
      - gadgetsmenu.commands.info
      - gadgetsmenu.commands.namepet
      - gadgetsmenu.commands.permission
      - gadgetsmenu.commands.reload
      - gadgetsmenu.cooldown.bypass
      - gadgetsmenu.link
  gadgetsmenu.hats.*:
    default: op
    description: Let a player to use all Hats.
    children:
      - gadgetsmenu.hats.
  gadgetsmenu.particles.*:
    default: op
    description: Let a player to use all Particles.
    children:
      - gadgetsmenu.particles.watersplash
      - gadgetsmenu.particles.dripwater
      - gadgetsmenu.particles.driplava
      - gadgetsmenu.particles.crit
      - gadgetsmenu.particles.magiccrit
      - gadgetsmenu.particles.spell
      - gadgetsmenu.particles.instantspell
      - gadgetsmenu.particles.mobspell
      - gadgetsmenu.particles.witchspell
      - gadgetsmenu.particles.angryvillager
      - gadgetsmenu.particles.happyvillager
      - gadgetsmenu.particles.townaura
      - gadgetsmenu.particles.note
      - gadgetsmenu.particles.portal
      - gadgetsmenu.particles.enchantment
      - gadgetsmenu.particles.flame
      - gadgetsmenu.particles.redstone
      - gadgetsmenu.particles.heart
      - gadgetsmenu.particles.fireworkspark
      - gadgetsmenu.particles.smoke
      - gadgetsmenu.particles.endrod
      - gadgetsmenu.particles.dragonbreath
      - gadgetsmenu.particles.damageindicator
  gadgetsmenu.wardrobe.*:
    default: op
    description: Let a player to use all Wardrobe.
    children:
      - gadgetsmenu.wardrobe.aqua.helmet
      - gadgetsmenu.wardrobe.black.helmet
      - gadgetsmenu.wardrobe.blue.helmet
      - gadgetsmenu.wardrobe.fuchsia.helmet
      - gadgetsmenu.wardrobe.gray.helmet
      - gadgetsmenu.wardrobe.green.helmet
      - gadgetsmenu.wardrobe.lime.helmet
      - gadgetsmenu.wardrobe.maroon.helmet
      - gadgetsmenu.wardrobe.navy.helmet
      - gadgetsmenu.wardrobe.olive.helmet
      - gadgetsmenu.wardrobe.orange.helmet
      - gadgetsmenu.wardrobe.purple.helmet
      - gadgetsmenu.wardrobe.red.helmet
      - gadgetsmenu.wardrobe.silver.helmet
      - gadgetsmenu.wardrobe.teal.helmet
      - gadgetsmenu.wardrobe.white.helmet
      - gadgetsmenu.wardrobe.yellow.helmet
      - gadgetsmenu.wardrobe.aqua.chestplate
      - gadgetsmenu.wardrobe.black.chestplate
      - gadgetsmenu.wardrobe.blue.chestplate
      - gadgetsmenu.wardrobe.fuchsia.chestplate
      - gadgetsmenu.wardrobe.gray.chestplate
      - gadgetsmenu.wardrobe.green.chestplate
      - gadgetsmenu.wardrobe.lime.chestplate
      - gadgetsmenu.wardrobe.maroon.chestplate
      - gadgetsmenu.wardrobe.navy.chestplate
      - gadgetsmenu.wardrobe.olive.chestplate
      - gadgetsmenu.wardrobe.orange.chestplate
      - gadgetsmenu.wardrobe.purple.chestplate
      - gadgetsmenu.wardrobe.red.chestplate
      - gadgetsmenu.wardrobe.silver.chestplate
      - gadgetsmenu.wardrobe.teal.chestplate
      - gadgetsmenu.wardrobe.white.chestplate
      - gadgetsmenu.wardrobe.yellow.chestplate
      - gadgetsmenu.wardrobe.aqua.leggings
      - gadgetsmenu.wardrobe.black.leggings
      - gadgetsmenu.wardrobe.blue.leggings
      - gadgetsmenu.wardrobe.fuchsia.leggings
      - gadgetsmenu.wardrobe.gray.leggings
      - gadgetsmenu.wardrobe.green.leggings
      - gadgetsmenu.wardrobe.lime.leggings
      - gadgetsmenu.wardrobe.maroon.leggings
      - gadgetsmenu.wardrobe.navy.leggings
      - gadgetsmenu.wardrobe.olive.leggings
      - gadgetsmenu.wardrobe.orange.leggings
      - gadgetsmenu.wardrobe.purple.leggings
      - gadgetsmenu.wardrobe.red.leggings
      - gadgetsmenu.wardrobe.silver.leggings
      - gadgetsmenu.wardrobe.teal.leggings
      - gadgetsmenu.wardrobe.white.leggings
      - gadgetsmenu.wardrobe.yellow.leggings
      - gadgetsmenu.wardrobe.aqua.boots
      - gadgetsmenu.wardrobe.black.boots
      - gadgetsmenu.wardrobe.blue.boots
      - gadgetsmenu.wardrobe.fuchsia.boots
      - gadgetsmenu.wardrobe.gray.boots
      - gadgetsmenu.wardrobe.green.boots
      - gadgetsmenu.wardrobe.lime.boots
      - gadgetsmenu.wardrobe.maroon.boots
      - gadgetsmenu.wardrobe.navy.boots
      - gadgetsmenu.wardrobe.olive.boots
      - gadgetsmenu.wardrobe.orange.boots
      - gadgetsmenu.wardrobe.purple.boots
      - gadgetsmenu.wardrobe.red.boots
      - gadgetsmenu.wardrobe.silver.boots
      - gadgetsmenu.wardrobe.teal.boots
      - gadgetsmenu.wardrobe.white.boots
      - gadgetsmenu.wardrobe.yellow.boots
  gadgetsmenu.discoarmor.*:
    default: op
    description: Let a player to use all DiscoArmor.
    children:
      - gadgetsmenu.discoarmor.helmet
      - gadgetsmenu.discoarmor.chestplate
      - gadgetsmenu.discoarmor.leggings
      - gadgetsmenu.discoarmor.boots
  gadgetsmenu.gadgets.*:
    default: op
    description: Let a player to use all gadgets.
    children:
      - gadgetsmenu.gadgets.paintballgun
      - gadgetsmenu.gadgets.explosivebow
      - gadgetsmenu.gadgets.batlauncher
      - gadgetsmenu.gadgets.letitsnow
      - gadgetsmenu.gadgets.firetrail
      - gadgetsmenu.gadgets.partypopper
      - gadgetsmenu.gadgets.tntfountain
      - gadgetsmenu.gadgets.teleportstick
      - gadgetsmenu.gadgets.melonlauncher
      - gadgetsmenu.gadgets.painttrail
      - gadgetsmenu.gadgets.explodingsheep
      - gadgetsmenu.gadgets.creeperastronaut
      - gadgetsmenu.gadgets.ghosts
      - gadgetsmenu.gadgets.poopbomb
      - gadgetsmenu.gadgets.parachute
      - gadgetsmenu.gadgets.discoball
      - gadgetsmenu.gadgets.rocket
      - gadgetsmenu.gadgets.goldfountain
  gadgetsmenu.pets.*:
    default: op
    description: Let a player to use all Pets.
    children:
      - gadgetsmenu.pets.
  gadgetsmenu.morphs.*:
    default: op
    description: Let a player to use all Morphs.
    children:
      - gadgetsmenu.morphs.pig
      - gadgetsmenu.morphs.cow
      - gadgetsmenu.morphs.enderman
      - gadgetsmenu.morphs.chicken
      - gadgetsmenu.morphs.spider
      - gadgetsmenu.morphs.sheep
      - gadgetsmenu.morphs.skeleton
      - gadgetsmenu.morphs.creeper
      - gadgetsmenu.morphs.blaze
      - gadgetsmenu.morphs.zombie
      - gadgetsmenu.morphs.irongolem
      - gadgetsmenu.morphs.witch
      - gadgetsmenu.morphs.snowman
      - gadgetsmenu.morphs.guardian
  gadgetsmenu.banners.*:
    default: op
    description: Let a player to use all Banners.
    children:
      - gadgetsmenu.banners.snowbunny
      - gadgetsmenu.banners.reindeer
      - gadgetsmenu.banners.holidaytree
      - gadgetsmenu.banners.santa
      - gadgetsmenu.banners.holidaywreath
      - gadgetsmenu.banners.heart
  gadgetsmenu.emotes.*:
    default: op
    description: Let a player to use all Emotes.
    children:
      - gadgetsmenu.emotes.smile
      - gadgetsmenu.emotes.cool
      - gadgetsmenu.emotes.wink
